name: Build ESP32

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install dependencies
        run: |
          arduino-cli lib install "ESPAsyncWebServer"
          arduino-cli lib install "AsyncTCP"
          # ESPAsyncWiFiManager is added manually

      - name: Compile sketch
        run: |
          arduino-cli compile \
            --fqbn esp32:esp32:esp32dev \
            --libraries lib \
            esp32_lcd_g4_s2_www_ok
