name: Build ESP32 Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Update core index and install ESP32 core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Install required libraries
      run: |
        arduino-cli lib update-index
        arduino-cli lib install "AsyncTCP"
        arduino-cli lib install "ESPAsyncWebServer"

    - name: Clone ESPAsyncWiFiManager library into project libraries folder
      run: |
        mkdir -p esp32_lcd_g4_s2_www_ok/libraries
        git clone --depth 1 https://github.com/khoih-prog/ESPAsync_WiFiManager.git esp32_lcd_g4_s2_www_ok/libraries/ESPAsyncWiFiManager

    - name: Compile Arduino sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32doit-devkit-v1 esp32_lcd_g4_s2_www_ok --verbose
