name: Build Arduino Project (ESP32)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install ESP32 core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Install required libraries from Arduino Library Manager
      run: |
        arduino-cli lib update-index
        arduino-cli lib install "AsyncTCP"
        arduino-cli lib install "ESPAsyncWebServer"

    - name: Install ESPAsyncWiFiManager from GitHub
      run: |
        git clone https://github.com/khoih-prog/ESPAsyncWiFiManager.git /tmp/ESPAsyncWiFiManager
        arduino-cli lib install /tmp/ESPAsyncWiFiManager

    - name: Install AsyncElegantOTA from GitHub
      run: |
        git clone https://github.com/ayushsharma82/AsyncElegantOTA.git /tmp/AsyncElegantOTA
        mkdir -p /tmp/AsyncElegantOTA_lib
        cp -r /tmp/AsyncElegantOTA/src /tmp/AsyncElegantOTA_lib/AsyncElegantOTA
        arduino-cli lib install /tmp/AsyncElegantOTA_lib/AsyncElegantOTA

    - name: Compile sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32doit-devkit-v1 esp32_lcd_g4_s2_www_ok/esp32_lcd_g4_s2_www_ok.ino
        mkdir -p output
        cp ./build/esp32.esp32.esp32doit-devkit-v1/esp32_lcd_g4_s2_www_ok.ino.bin ./output/

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: output/
