name: Build ESP32 Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install ESP32 core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Install libraries from Library Manager
      run: |
        arduino-cli lib update-index
        arduino-cli lib install "AsyncTCP"
        arduino-cli lib install "ESPAsyncWebServer"
        arduino-cli lib install "ESPAsyncTCP"

    - name: Clone ESPAsyncWiFiManager manually
      run: |
        mkdir -p arduino-libs
        git clone https://github.com/khoih-prog/ESPAsync_WiFiManager.git arduino-libs/ESPAsyncWiFiManager

    - name: Compile sketch
      run: |
        arduino-cli compile \
          --fqbn esp32:esp32:esp32doit-devkit-v1 \
          --libraries arduino-libs \
          esp32_lcd_g4_s2_www_ok \
          --verbose
