name: Build supla-test with Arduino CLI - Debug FQBN

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Show Arduino CLI version
        run: arduino-cli version

      - name: Update core index and install ESP32
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Show installed cores
        run: arduino-cli core list

      - name: Show available boards
        run: arduino-cli board listall

      - name: List installed packages folder
        run: ls -l ~/.arduino15/packages/esp32/hardware/esp32

      - name: Try to compile supla-test with guessed FQBN (will likely fail)
        run: arduino-cli compile --fqbn esp32:esp32:esp32dev supla-test
