name: Build Arduino Project (ESP32)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Update library index and install required libraries
        run: |
          arduino-cli lib update-index
          arduino-cli lib install "AsyncTCP"
          arduino-cli lib install "ESPAsyncWebServer"
          arduino-cli lib install "ElegantOTA"

      - name: Clone ESPAsyncWiFiManager library into sketch libraries folder
        run: |
          mkdir -p $GITHUB_WORKSPACE/esp32_lcd_g4_s2_www_ok/libraries
          git clone --depth 1 --branch v1.15.1 https://github.com/khoih-prog/ESPAsync_WiFiManager.git $GITHUB_WORKSPACE/esp32_lcd_g4_s2_www_ok/libraries/ESPAsyncWiFiManager

      - name: List sketch and libraries content for debugging
        run: ls -lR $GITHUB_WORKSPACE/esp32_lcd_g4_s2_www_ok

      - name: Compile sketch
        run: |
          arduino-cli compile \
            --fqbn esp32:esp32:esp32doit-devkit-v1 \
            --libraries $GITHUB_WORKSPACE/esp32_lcd_g4_s2_www_ok/libraries \
            --build-path $GITHUB_WORKSPACE/build \
            $GITHUB_WORKSPACE/esp32_lcd_g4_s2_www_ok/esp32_lcd_g4_s2_www_ok.ino --verbose
          mkdir -p output
          cp $GITHUB_WORKSPACE/build/esp32.esp32.esp32doit-devkit-v1/esp32_lcd_g4_s2_www_ok.ino.bin output/

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: output/
