name: Build Arduino Project (ESP32)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Update library index and install required libraries
        run: |
          arduino-cli lib update-index
          arduino-cli lib install "AsyncTCP"
          arduino-cli lib install "ESPAsyncWebServer"
          arduino-cli lib install "ElegantOTA"

      - name: Download ESPAsyncWiFiManager library into sketch libraries folder
        run: |
          wget https://github.com/khoih-prog/ESPAsync_WiFiManager/archive/refs/tags/v1.15.1.zip -O ESPAsyncWiFiManager.zip
          unzip ESPAsyncWiFiManager.zip
          mkdir -p esp32_lcd_g4_s2_www_ok/libraries
          mv ESPAsync_WiFiManager-1.15.1 esp32_lcd_g4_s2_www_ok/libraries/ESPAsyncWiFiManager

      - name: Compile sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32doit-devkit-v1 esp32_lcd_g4_s2_www_ok/esp32_lcd_g4_s2_www_ok.ino
          mkdir -p output
          cp ./build/esp32.esp32.esp32doit-devkit-v1/esp32_lcd_g4_s2_www_ok.ino.bin ./output/

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: output/
