name: Arduino CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        export PATH=$HOME/.arduino15/bin:$PATH
        arduino-cli version

    - name: Update and install ESP32 core
      run: |
        ~/.arduino15/arduino-cli core update-index
        ~/.arduino15/arduino-cli core install esp32:esp32

    - name: Compile supla-test.ino
      run: |
        ~/.arduino15/arduino-cli compile --fqbn esp32:esp32:esp32dev supla-test/supla-test.ino
