name: Build with Arduino CLI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "export PATH=$PATH:$(pwd)/bin" >> $GITHUB_ENV

      - name: Verify Arduino CLI version
        run: arduino-cli version

      - name: Set up Arduino Core for ESP32
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Compile supla-test.ino
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32dev supla-test.ino
